defmodule Conductor.Repo.Migrations.AddModelsToRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:runs) do
      add :models, :map
    end
  end

  def down do
    alter table(:runs) do
      remove :models
    end
  end
end
