defmodule Conductor.Repo.Migrations.ReconcileExistingSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:runs, [:issue_key, :attempt], name: "runs_issue_key_attempt_index")
  end

  def down do
    drop_if_exists unique_index(:runs, [:issue_key, :attempt],
                     name: "runs_issue_key_attempt_index"
                   )
  end
end
