defmodule Conductor.Repo.Migrations.RecordRunStatusChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:runs_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :status, :text, null: false, default: "picked_up"

      add :version_source_id,
          references(:runs,
            column: :id,
            name: "runs_versions_version_source_id_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:runs_versions, [:version_source_id])
  end

  def down do
    drop_if_exists index(:runs_versions, [:version_source_id])

    drop constraint(:runs_versions, "runs_versions_version_source_id_fkey")

    drop table(:runs_versions)
  end
end
