defmodule Conductor.Repo.Migrations.GenerateResourceSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :project_owner, :string, null: false
      add :runner_login, :string, null: false
      add :pickup_status, :string, null: false
      add :active_status, :string, null: false
      add :handoff_status, :string, null: false
      add :done_status, :string, null: false, default: "Done"
      add :project_number, :integer, null: false, default: 0
      add :item_filter, :string
      add :enabled, :boolean, null: false, default: true
      add :inserted_at, :utc_datetime, null: false
      add :updated_at, :utc_datetime, null: false
      add :repo_id, :bigint, null: false
    end

    create unique_index(:projects, [:repo_id, :project_owner, :project_number],
             name: "projects_repo_id_project_owner_project_number_index"
           )

    create table(:questions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :qid, :string, null: false
      add :text, :text, null: false
      add :answer, :text
      add :answered_at, :utc_datetime
      add :inserted_at, :utc_datetime, null: false
      add :updated_at, :utc_datetime, null: false
      add :run_id, :string, null: false
    end

    create unique_index(:questions, [:run_id, :qid], name: "questions_run_id_qid_index")

    create table(:repos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:projects) do
      modify :repo_id,
             references(:repos,
               column: :id,
               name: "projects_repo_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:repos) do
      add :name, :string, null: false
      add :clone_url, :string, null: false
      add :owner, :string, null: false
      add :slug, :string, null: false
      add :base_branch, :string
      add :setup_script, :text
      add :test_command, :string
      add :inserted_at, :utc_datetime, null: false
      add :updated_at, :utc_datetime, null: false
    end

    create unique_index(:repos, [:name], name: "repos_name_index")

    create table(:run_events, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :conversation, :integer, null: false
      add :role, :string, null: false
      add :entry, :string, null: false
      add :position, :integer
      add :kind, :string, null: false
      add :payload, :map, null: false
      add :inserted_at, :utc_datetime, null: false
      add :run_id, :string, null: false
    end

    create unique_index(:run_events, [:run_id, :conversation, :entry],
             name: "run_events_run_id_conversation_entry_index"
           )

    create table(:runs, primary_key: false) do
      add :id, :string, null: false, primary_key: true
    end

    alter table(:questions) do
      modify :run_id,
             references(:runs,
               column: :id,
               name: "questions_run_id_fkey",
               type: :string,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:run_events) do
      modify :run_id,
             references(:runs,
               column: :id,
               name: "run_events_run_id_fkey",
               type: :string,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:runs) do
      add :issue_key, :string, null: false
      add :attempt, :integer, null: false
      add :issue_snapshot, :map
      add :workspace_path, :string
      add :branch, :string
      add :outcome, :string
      add :summary, :text
      add :error, :text
      add :pr_url, :string
      add :inserted_at, :utc_datetime, null: false
      add :updated_at, :utc_datetime, null: false
      add :status, :string, null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "runs_project_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:runs, [:issue_key, :attempt], name: "runs_issue_key_attempt_index")

    create index(:runs, [:issue_key], name: "runs_issue_key_index")

    create index(:runs, [:status], name: "runs_status_index")

    create table(:settings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :models, :map, null: false, default: %{}
      add :max_concurrent, :integer, null: false, default: 3
      add :prune_days, :integer, null: false, default: 7
      add :inserted_at, :utc_datetime, null: false
      add :updated_at, :utc_datetime, null: false
    end
  end

  def down do
    drop table(:settings)

    drop_if_exists index(:runs, [:status], name: "runs_status_index")

    drop_if_exists index(:runs, [:issue_key], name: "runs_issue_key_index")

    drop constraint(:runs, "runs_project_id_fkey")

    drop_if_exists unique_index(:runs, [:issue_key, :attempt],
                     name: "runs_issue_key_attempt_index"
                   )

    alter table(:runs) do
      remove :project_id
      remove :status
      remove :updated_at
      remove :inserted_at
      remove :pr_url
      remove :error
      remove :summary
      remove :outcome
      remove :branch
      remove :workspace_path
      remove :issue_snapshot
      remove :attempt
      remove :issue_key
    end

    drop constraint(:run_events, "run_events_run_id_fkey")

    alter table(:run_events) do
      modify :run_id, :string
    end

    drop constraint(:questions, "questions_run_id_fkey")

    alter table(:questions) do
      modify :run_id, :string
    end

    drop table(:runs)

    drop_if_exists unique_index(:run_events, [:run_id, :conversation, :entry],
                     name: "run_events_run_id_conversation_entry_index"
                   )

    drop table(:run_events)

    drop_if_exists unique_index(:repos, [:name], name: "repos_name_index")

    alter table(:repos) do
      remove :updated_at
      remove :inserted_at
      remove :test_command
      remove :setup_script
      remove :base_branch
      remove :slug
      remove :owner
      remove :clone_url
      remove :name
    end

    drop constraint(:projects, "projects_repo_id_fkey")

    alter table(:projects) do
      modify :repo_id, :bigint
    end

    drop table(:repos)

    drop_if_exists unique_index(:questions, [:run_id, :qid], name: "questions_run_id_qid_index")

    drop table(:questions)

    drop_if_exists unique_index(:projects, [:repo_id, :project_owner, :project_number],
                     name: "projects_repo_id_project_owner_project_number_index"
                   )

    drop table(:projects)
  end
end
